// GENERATED by scripts/pin-grammars.mjs. Do not edit; change PINS there and rerun it.
//
// The tree-sitter grammars `diffninja grammars install` may download, with the
// registry's integrity hash of every tarball (npm lockfile v3). Nothing outside
// this file is ever installed on a reviewer's behalf.

/** The grammar packages and the exact version of each. */
export const GRAMMAR_PINS = {
  "@tree-sitter-grammars/tree-sitter-lua": "0.2.0",
  "@tree-sitter-grammars/tree-sitter-zig": "1.1.2",
  "tree-sitter-bash": "0.25.1",
  "tree-sitter-c": "0.24.1",
  "tree-sitter-c-sharp": "0.23.1",
  "tree-sitter-cpp": "0.23.4",
  "tree-sitter-elixir": "0.3.5",
  "tree-sitter-go": "0.25.0",
  "tree-sitter-haskell": "0.23.1",
  "tree-sitter-java": "0.23.5",
  "tree-sitter-kotlin": "0.3.8",
  "tree-sitter-ocaml": "0.24.2",
  "tree-sitter-perl": "2.0.0",
  "tree-sitter-php": "0.24.2",
  "tree-sitter-python": "0.25.0",
  "tree-sitter-ruby": "0.23.1",
  "tree-sitter-rust": "0.24.0",
  "tree-sitter-scala": "0.24.0",
  "tree-sitter-solidity": "1.2.13",
  "tree-sitter-swift": "0.7.1"
} as const;

/** Pinned packages that ship no prebuilt binary and load only after `grammars install --build`. */
export const GRAMMAR_BUILD_ONLY = ["tree-sitter-kotlin","tree-sitter-perl"] as const;

/** The cache directory's package.json; its dependencies are GRAMMAR_PINS. */
export const GRAMMAR_PACKAGE_JSON = {
  "name": "diffninja-grammar-cache",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "@tree-sitter-grammars/tree-sitter-lua": "0.2.0",
    "@tree-sitter-grammars/tree-sitter-zig": "1.1.2",
    "tree-sitter-bash": "0.25.1",
    "tree-sitter-c": "0.24.1",
    "tree-sitter-c-sharp": "0.23.1",
    "tree-sitter-cpp": "0.23.4",
    "tree-sitter-elixir": "0.3.5",
    "tree-sitter-go": "0.25.0",
    "tree-sitter-haskell": "0.23.1",
    "tree-sitter-java": "0.23.5",
    "tree-sitter-kotlin": "0.3.8",
    "tree-sitter-ocaml": "0.24.2",
    "tree-sitter-perl": "2.0.0",
    "tree-sitter-php": "0.24.2",
    "tree-sitter-python": "0.25.0",
    "tree-sitter-ruby": "0.23.1",
    "tree-sitter-rust": "0.24.0",
    "tree-sitter-scala": "0.24.0",
    "tree-sitter-solidity": "1.2.13",
    "tree-sitter-swift": "0.7.1"
  }
} as const;

/** The cache directory's package-lock.json, exactly as npm resolved it. */
export const GRAMMAR_PACKAGE_LOCK = {
  "name": "diffninja-grammar-cache",
  "version": "1.0.0",
  "lockfileVersion": 3,
  "requires": true,
  "packages": {
    "": {
      "name": "diffninja-grammar-cache",
      "version": "1.0.0",
      "dependencies": {
        "@tree-sitter-grammars/tree-sitter-lua": "0.2.0",
        "@tree-sitter-grammars/tree-sitter-zig": "1.1.2",
        "tree-sitter-bash": "0.25.1",
        "tree-sitter-c": "0.24.1",
        "tree-sitter-c-sharp": "0.23.1",
        "tree-sitter-cpp": "0.23.4",
        "tree-sitter-elixir": "0.3.5",
        "tree-sitter-go": "0.25.0",
        "tree-sitter-haskell": "0.23.1",
        "tree-sitter-java": "0.23.5",
        "tree-sitter-kotlin": "0.3.8",
        "tree-sitter-ocaml": "0.24.2",
        "tree-sitter-perl": "2.0.0",
        "tree-sitter-php": "0.24.2",
        "tree-sitter-python": "0.25.0",
        "tree-sitter-ruby": "0.23.1",
        "tree-sitter-rust": "0.24.0",
        "tree-sitter-scala": "0.24.0",
        "tree-sitter-solidity": "1.2.13",
        "tree-sitter-swift": "0.7.1"
      }
    },
    "node_modules/@tree-sitter-grammars/tree-sitter-lua": {
      "version": "0.2.0",
      "resolved": "https://registry.npmjs.org/@tree-sitter-grammars/tree-sitter-lua/-/tree-sitter-lua-0.2.0.tgz",
      "integrity": "sha512-VPk971J3hBUNr7CpZJvgTU5UmEkW8iMQ0Sk6br4O3xL00XFEO4PCjSSGeYYakRgPAJiIR8J594UcBK+7ilBvqw==",
      "hasInstallScript": true,
      "license": "MIT",
      "dependencies": {
        "node-addon-api": "^8.0.0",
        "node-gyp-build": "^4.8.1"
      },
      "peerDependencies": {
        "tree-sitter": "^0.21.1"
      },
      "peerDependenciesMeta": {
        "tree_sitter": {
          "optional": true
        }
      }
    },
    "node_modules/@tree-sitter-grammars/tree-sitter-zig": {
      "version": "1.1.2",
      "resolved": "https://registry.npmjs.org/@tree-sitter-grammars/tree-sitter-zig/-/tree-sitter-zig-1.1.2.tgz",
      "integrity": "sha512-J0L31HZ2isy3F5zb2g5QWQOv2r/pbruQNL9ADhuQv2pn5BQOzxt80WcEJaYXBeuJ8GHxVT42slpCna8k1c8LOw==",
      "hasInstallScript": true,
      "license": "MIT",
      "dependencies": {
        "node-addon-api": "^8.3.0",
        "node-gyp-build": "^4.8.4"
      },
      "peerDependencies": {
        "tree-sitter": "^0.22.1"
      },
      "peerDependenciesMeta": {
        "tree-sitter": {
          "optional": true
        }
      }
    },
    "node_modules/isexe": {
      "version": "2.0.0",
      "resolved": "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz",
      "integrity": "sha512-RHxMLp9lnKHGHRng9QFhRCMbYAcVpn69smSGcq3f36xjgVVWThj4qqLbTLlq7Ssj8B+fIQ1EuCEGI2lKsyQeIw==",
      "license": "ISC"
    },
    "node_modules/node-addon-api": {
      "version": "8.9.2",
      "resolved": "https://registry.npmjs.org/node-addon-api/-/node-addon-api-8.9.2.tgz",
      "integrity": "sha512-VijLXbi3UACN69I0JVXJsX4tjACjNoQDgv2gTF6sx2wWEi8tkSg2eX8p5gSIFi8z2+DL3oHmY6OyKce38SDolg==",
      "license": "MIT",
      "engines": {
        "node": "^18 || ^20 || >= 21"
      }
    },
    "node_modules/node-gyp-build": {
      "version": "4.8.4",
      "resolved": "https://registry.npmjs.org/node-gyp-build/-/node-gyp-build-4.8.4.tgz",
      "integrity": "sha512-LA4ZjwlnUblHVgq0oBF3Jl/6h/Nvs5fzBLwdEF4nuxnFdsfajde4WfxtJr3CaiH+F6ewcIB/q4jQ4UzPyid+CQ==",
      "license": "MIT",
      "bin": {
        "node-gyp-build": "bin.js",
        "node-gyp-build-optional": "optional.js",
        "node-gyp-build-test": "build-test.js"
      }
    },
    "node_modules/tree-sitter-bash": {
      "version": "0.25.1",
      "resolved": "https://registry.npmjs.org/tree-sitter-bash/-/tree-sitter-bash-0.25.1.tgz",
      "integrity": "sha512-7hMytuYIMoXOq24yRulgIxthE9YmggZIOHCyPTTuJcu6EU54tYD+4G39cUb28kxC6jMf/AbPfWGLQtgPTdh3xw==",
      "hasInstallScript": true,
      "license": "MIT",
      "dependencies": {
        "node-addon-api": "^8.2.1",
        "node-gyp-build": "^4.8.2"
      },
      "peerDependencies": {
        "tree-sitter": "^0.25.0"
      },
      "peerDependenciesMeta": {
        "tree-sitter": {
          "optional": true
        }
      }
    },
    "node_modules/tree-sitter-c": {
      "version": "0.24.1",
      "resolved": "https://registry.npmjs.org/tree-sitter-c/-/tree-sitter-c-0.24.1.tgz",
      "integrity": "sha512-lkYwWN3SRecpvaeqmFKkuPNR3ZbtnvHU+4XAEEkJdrp3JfSp2pBrhXOtvfsENUneye76g889Y0ddF2DM0gEDpA==",
      "hasInstallScript": true,
      "license": "MIT",
      "dependencies": {
        "node-addon-api": "^8.3.1",
        "node-gyp-build": "^4.8.4"
      },
      "peerDependencies": {
        "tree-sitter": "^0.22.4"
      },
      "peerDependenciesMeta": {
        "tree-sitter": {
          "optional": true
        }
      }
    },
    "node_modules/tree-sitter-c-sharp": {
      "version": "0.23.1",
      "resolved": "https://registry.npmjs.org/tree-sitter-c-sharp/-/tree-sitter-c-sharp-0.23.1.tgz",
      "integrity": "sha512-9zZ4FlcTRWWfRf6f4PgGhG8saPls6qOOt75tDfX7un9vQZJmARjPrAC6yBNCX2T/VKcCjIDbgq0evFaB3iGhQw==",
      "hasInstallScript": true,
      "license": "MIT",
      "dependencies": {
        "node-addon-api": "^8.2.2",
        "node-gyp-build": "^4.8.2"
      },
      "peerDependencies": {
        "tree-sitter": "^0.21.1"
      },
      "peerDependenciesMeta": {
        "tree-sitter": {
          "optional": true
        }
      }
    },
    "node_modules/tree-sitter-cli": {
      "version": "0.23.2",
      "resolved": "https://registry.npmjs.org/tree-sitter-cli/-/tree-sitter-cli-0.23.2.tgz",
      "integrity": "sha512-kPPXprOqREX+C/FgUp2Qpt9jd0vSwn+hOgjzVv/7hapdoWpa+VeWId53rf4oNNd29ikheF12BYtGD/W90feMbA==",
      "hasInstallScript": true,
      "license": "MIT",
      "bin": {
        "tree-sitter": "cli.js"
      },
      "engines": {
        "node": ">=12.0.0"
      }
    },
    "node_modules/tree-sitter-cpp": {
      "version": "0.23.4",
      "resolved": "https://registry.npmjs.org/tree-sitter-cpp/-/tree-sitter-cpp-0.23.4.tgz",
      "integrity": "sha512-qR5qUDyhZ5jJ6V8/umiBxokRbe89bCGmcq/dk94wI4kN86qfdV8k0GHIUEKaqWgcu42wKal5E97LKpLeVW8sKw==",
      "hasInstallScript": true,
      "license": "MIT",
      "dependencies": {
        "node-addon-api": "^8.2.1",
        "node-gyp-build": "^4.8.2",
        "tree-sitter-c": "^0.23.1"
      },
      "peerDependencies": {
        "tree-sitter": "^0.21.1"
      },
      "peerDependenciesMeta": {
        "tree-sitter": {
          "optional": true
        }
      }
    },
    "node_modules/tree-sitter-cpp/node_modules/tree-sitter-c": {
      "version": "0.23.6",
      "resolved": "https://registry.npmjs.org/tree-sitter-c/-/tree-sitter-c-0.23.6.tgz",
      "integrity": "sha512-0dxXKznVyUA0s6PjNolJNs2yF87O5aL538A/eR6njA5oqX3C3vH4vnx3QdOKwuUdpKEcFdHuiDpRKLLCA/tjvQ==",
      "hasInstallScript": true,
      "license": "MIT",
      "dependencies": {
        "node-addon-api": "^8.3.0",
        "node-gyp-build": "^4.8.4"
      },
      "peerDependencies": {
        "tree-sitter": "^0.22.1"
      },
      "peerDependenciesMeta": {
        "tree-sitter": {
          "optional": true
        }
      }
    },
    "node_modules/tree-sitter-elixir": {
      "version": "0.3.5",
      "resolved": "https://registry.npmjs.org/tree-sitter-elixir/-/tree-sitter-elixir-0.3.5.tgz",
      "integrity": "sha512-xozQMvYK0aSolcQZAx2d84Xe/YMWFuRPYFlLVxO01bM2GITh5jyiIp0TqPCQa8754UzRAI7A83hZmfiYub5TZQ==",
      "hasInstallScript": true,
      "license": "Apache-2.0",
      "dependencies": {
        "node-addon-api": "^7.1.0",
        "node-gyp-build": "^4.8.0"
      },
      "peerDependencies": {
        "tree-sitter": "^0.21.0"
      }
    },
    "node_modules/tree-sitter-elixir/node_modules/node-addon-api": {
      "version": "7.1.1",
      "resolved": "https://registry.npmjs.org/node-addon-api/-/node-addon-api-7.1.1.tgz",
      "integrity": "sha512-5m3bsyrjFWE1xf7nz7YXdN4udnVtXK6/Yfgn5qnahL6bCkf2yKt4k3nuTKAtT4r3IG8JNR2ncsIMdZuAzJjHQQ==",
      "license": "MIT"
    },
    "node_modules/tree-sitter-go": {
      "version": "0.25.0",
      "resolved": "https://registry.npmjs.org/tree-sitter-go/-/tree-sitter-go-0.25.0.tgz",
      "integrity": "sha512-APBc/Dq3xz/e35Xpkhb1blu5UgW+2E3RyGWawZSCNcbGwa7jhSQPS8KsUupuzBla8PCo8+lz9W/JDJjmfRa2tw==",
      "hasInstallScript": true,
      "license": "MIT",
      "dependencies": {
        "node-addon-api": "^8.3.1",
        "node-gyp-build": "^4.8.4"
      },
      "peerDependencies": {
        "tree-sitter": "^0.25.0"
      },
      "peerDependenciesMeta": {
        "tree-sitter": {
          "optional": true
        }
      }
    },
    "node_modules/tree-sitter-haskell": {
      "version": "0.23.1",
      "resolved": "https://registry.npmjs.org/tree-sitter-haskell/-/tree-sitter-haskell-0.23.1.tgz",
      "integrity": "sha512-qG4CYhejveu9DLMLEGBz/n9/TTeGSFLC6wniwOgG6m8/v7Dng8qR0ob0EVG7+XH+9WiOxohpGA23EhceWuxY4w==",
      "hasInstallScript": true,
      "license": "MIT",
      "dependencies": {
        "node-addon-api": "^8.2.2",
        "node-gyp-build": "^4.8.2"
      },
      "peerDependencies": {
        "tree-sitter": "^0.21.1"
      },
      "peerDependenciesMeta": {
        "tree-sitter": {
          "optional": true
        }
      }
    },
    "node_modules/tree-sitter-java": {
      "version": "0.23.5",
      "resolved": "https://registry.npmjs.org/tree-sitter-java/-/tree-sitter-java-0.23.5.tgz",
      "integrity": "sha512-Yju7oQ0Xx7GcUT01mUglPP+bYfvqjNCGdxqigTnew9nLGoII42PNVP3bHrYeMxswiCRM0yubWmN5qk+zsg0zMA==",
      "hasInstallScript": true,
      "license": "MIT",
      "dependencies": {
        "node-addon-api": "^8.2.2",
        "node-gyp-build": "^4.8.2"
      },
      "peerDependencies": {
        "tree-sitter": "^0.21.1"
      },
      "peerDependenciesMeta": {
        "tree-sitter": {
          "optional": true
        }
      }
    },
    "node_modules/tree-sitter-kotlin": {
      "version": "0.3.8",
      "resolved": "https://registry.npmjs.org/tree-sitter-kotlin/-/tree-sitter-kotlin-0.3.8.tgz",
      "integrity": "sha512-A4obq6bjzmYrA+F0JLLoheFPcofFkctNaZSpnDd+GPn1SfVZLY4/GG4C0cYVBTOShuPBGGAOPLM1JWLZQV4m1g==",
      "hasInstallScript": true,
      "license": "MIT",
      "dependencies": {
        "node-addon-api": "^7.1.0",
        "node-gyp-build": "^4.8.0"
      },
      "peerDependencies": {
        "tree-sitter": "^0.21.0"
      },
      "peerDependenciesMeta": {
        "tree_sitter": {
          "optional": true
        }
      }
    },
    "node_modules/tree-sitter-kotlin/node_modules/node-addon-api": {
      "version": "7.1.1",
      "resolved": "https://registry.npmjs.org/node-addon-api/-/node-addon-api-7.1.1.tgz",
      "integrity": "sha512-5m3bsyrjFWE1xf7nz7YXdN4udnVtXK6/Yfgn5qnahL6bCkf2yKt4k3nuTKAtT4r3IG8JNR2ncsIMdZuAzJjHQQ==",
      "license": "MIT"
    },
    "node_modules/tree-sitter-ocaml": {
      "version": "0.24.2",
      "resolved": "https://registry.npmjs.org/tree-sitter-ocaml/-/tree-sitter-ocaml-0.24.2.tgz",
      "integrity": "sha512-H0RAeCepIyXyTPCQra6yMd7Bn5ZBYkIaddzdLNwVZpM9mCe2e8av+3O6Ojl7Z8YHrV/kYsfHvI2y+Hh7qzcYQQ==",
      "hasInstallScript": true,
      "license": "MIT",
      "dependencies": {
        "node-addon-api": "^8.3.0",
        "node-gyp-build": "^4.8.4"
      },
      "peerDependencies": {
        "tree-sitter": "^0.22.4"
      },
      "peerDependenciesMeta": {
        "tree-sitter": {
          "optional": true
        }
      }
    },
    "node_modules/tree-sitter-perl": {
      "version": "2.0.0",
      "resolved": "https://registry.npmjs.org/tree-sitter-perl/-/tree-sitter-perl-2.0.0.tgz",
      "integrity": "sha512-sKZfFIvw5S18UHHAMe7rRpuZzzkLxaeslmZeflPlFKLfKAWCT8XAIqu/IBWzWR5phkMTZM3DxqOxX2IXC51SdA==",
      "hasInstallScript": true,
      "license": "MIT",
      "dependencies": {
        "node-addon-api": "^8.3.0",
        "node-gyp-build": "^4.8.4"
      },
      "engines": {
        "node": ">= 20.0.0"
      },
      "peerDependencies": {
        "tree-sitter": ">=0.25.0"
      },
      "peerDependenciesMeta": {
        "tree-sitter": {
          "optional": true
        }
      }
    },
    "node_modules/tree-sitter-php": {
      "version": "0.24.2",
      "resolved": "https://registry.npmjs.org/tree-sitter-php/-/tree-sitter-php-0.24.2.tgz",
      "integrity": "sha512-zwgAePc/HozNaWOOfwRAA+3p8yhuehRw8Fb7vn5qd2XjiIc93uJPryDTMYTSjBRjVIUg/KY6pM3rRzs8dSwKfw==",
      "hasInstallScript": true,
      "license": "MIT",
      "dependencies": {
        "node-addon-api": "^8.2.2",
        "node-gyp-build": "^4.8.2"
      },
      "peerDependencies": {
        "tree-sitter": "^0.22.4"
      },
      "peerDependenciesMeta": {
        "tree-sitter": {
          "optional": true
        }
      }
    },
    "node_modules/tree-sitter-python": {
      "version": "0.25.0",
      "resolved": "https://registry.npmjs.org/tree-sitter-python/-/tree-sitter-python-0.25.0.tgz",
      "integrity": "sha512-eCmJx6zQa35GxaCtQD+wXHOhYqBxEL+bp71W/s3fcDMu06MrtzkVXR437dRrCrbrDbyLuUDJpAgycs7ncngLXw==",
      "hasInstallScript": true,
      "license": "MIT",
      "dependencies": {
        "node-addon-api": "^8.5.0",
        "node-gyp-build": "^4.8.4"
      },
      "peerDependencies": {
        "tree-sitter": "^0.25.0"
      },
      "peerDependenciesMeta": {
        "tree-sitter": {
          "optional": true
        }
      }
    },
    "node_modules/tree-sitter-ruby": {
      "version": "0.23.1",
      "resolved": "https://registry.npmjs.org/tree-sitter-ruby/-/tree-sitter-ruby-0.23.1.tgz",
      "integrity": "sha512-d9/RXgWjR6HanN7wTYhS5bpBQLz1VkH048Vm3CodPGyJVnamXMGb8oEhDypVCBq4QnHui9sTXuJBBP3WtCw5RA==",
      "hasInstallScript": true,
      "license": "MIT",
      "dependencies": {
        "node-addon-api": "^8.2.2",
        "node-gyp-build": "^4.8.2"
      },
      "peerDependencies": {
        "tree-sitter": "^0.21.1"
      },
      "peerDependenciesMeta": {
        "tree-sitter": {
          "optional": true
        }
      }
    },
    "node_modules/tree-sitter-rust": {
      "version": "0.24.0",
      "resolved": "https://registry.npmjs.org/tree-sitter-rust/-/tree-sitter-rust-0.24.0.tgz",
      "integrity": "sha512-NWemUDf629Tfc90Y0Z55zuwPCAHkLxWnMf2RznYu4iBkkrQl2o/CHGB7Cr52TyN5F1DAx8FmUnDtCy9iUkXZEQ==",
      "hasInstallScript": true,
      "license": "MIT",
      "dependencies": {
        "node-addon-api": "^8.2.2",
        "node-gyp-build": "^4.8.4"
      },
      "peerDependencies": {
        "tree-sitter": "^0.22.1"
      },
      "peerDependenciesMeta": {
        "tree-sitter": {
          "optional": true
        }
      }
    },
    "node_modules/tree-sitter-scala": {
      "version": "0.24.0",
      "resolved": "https://registry.npmjs.org/tree-sitter-scala/-/tree-sitter-scala-0.24.0.tgz",
      "integrity": "sha512-vkMuAUrBZ1zZz2XcGDQk18Kz73JkpgaeXzbNVobPke0G35sd9jH32aUxG6OLRKM7et0TbsfqkWf4DeJoGk4K1g==",
      "hasInstallScript": true,
      "license": "MIT",
      "dependencies": {
        "node-addon-api": "^8.2.2",
        "node-gyp-build": "^4.8.2"
      },
      "peerDependencies": {
        "tree-sitter": "^0.21.1"
      },
      "peerDependenciesMeta": {
        "tree-sitter": {
          "optional": true
        }
      }
    },
    "node_modules/tree-sitter-solidity": {
      "version": "1.2.13",
      "resolved": "https://registry.npmjs.org/tree-sitter-solidity/-/tree-sitter-solidity-1.2.13.tgz",
      "integrity": "sha512-nO2AbcAuz2Qba8JnPNe/3FVjRRvGY3ApxSJ8UPIzfynJm4PYCMbBoXxxbprvMgjCbGYR/ZrHGIPKzXV7zBa+lQ==",
      "hasInstallScript": true,
      "license": "MIT",
      "dependencies": {
        "node-addon-api": "^8.2.2",
        "node-gyp-build": "^4.8.2",
        "yarn": "^1.22.21"
      },
      "peerDependencies": {
        "tree-sitter": "^0.25.0"
      },
      "peerDependenciesMeta": {
        "tree_sitter": {
          "optional": true
        }
      }
    },
    "node_modules/tree-sitter-swift": {
      "version": "0.7.1",
      "resolved": "https://registry.npmjs.org/tree-sitter-swift/-/tree-sitter-swift-0.7.1.tgz",
      "integrity": "sha512-pneKVTuGamaBsqqqfB9BvNQjktzh/0IVPR54jLB5Fq/JTDQwYHd0Wo6pVyZ5jAYpbztzq+rJ/rpL9ruxTmSoKw==",
      "hasInstallScript": true,
      "license": "MIT",
      "dependencies": {
        "node-addon-api": "^8.0.0",
        "node-gyp-build": "^4.8.0",
        "tree-sitter-cli": "^0.23",
        "which": "2.0.2"
      },
      "peerDependencies": {
        "tree-sitter": "^0.22.1"
      },
      "peerDependenciesMeta": {
        "tree_sitter": {
          "optional": true
        }
      }
    },
    "node_modules/which": {
      "version": "2.0.2",
      "resolved": "https://registry.npmjs.org/which/-/which-2.0.2.tgz",
      "integrity": "sha512-BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==",
      "license": "ISC",
      "dependencies": {
        "isexe": "^2.0.0"
      },
      "bin": {
        "node-which": "bin/node-which"
      },
      "engines": {
        "node": ">= 8"
      }
    },
    "node_modules/yarn": {
      "version": "1.22.22",
      "resolved": "https://registry.npmjs.org/yarn/-/yarn-1.22.22.tgz",
      "integrity": "sha512-prL3kGtyG7o9Z9Sv8IPfBNrWTDmXB4Qbes8A9rEzt6wkJV8mUvoirjU0Mp3GGAU06Y0XQyA3/2/RQFVuK7MTfg==",
      "hasInstallScript": true,
      "license": "BSD-2-Clause",
      "bin": {
        "yarn": "bin/yarn.js",
        "yarnpkg": "bin/yarn.js"
      },
      "engines": {
        "node": ">=4.0.0"
      }
    }
  }
} as const;
